version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 10
        commands:
            # Install dependencies needed for running tests
            - npm install

            # Upgrade AWS CLI to the latest version
            - pip install --upgrade awscli
    pre_build:
        commands:
            # Discover and run unit tests in the 'tests' directory
artifacts:
    type: zip
    files:
        - README.md
        - package.json
        - app.js
        - node_modules/**/*
        - public/**/*
        - style.css
        - cover-box-square.png
        - index.html
        - package.json
